export { Login } from  "./Login"
export { Register } from "./Register"
export { Perfil } from "./Perfil"
export { Mensagem } from "./Mensagem"
export { CadMessage } from "./CadMensagem"
export { Camera } from "./Camera"
export { Imagens } from "./Imagens"